#!/bin/bash

set -e 

#######################################################################
#                       Usage
########################################################################

function usage {
	echo ""
	echo "Usage: $0 [ARTIFACT] [NEXUS_URL]"
	exit 1
}


#######################################################################
#                       Parameter parsing
########################################################################

ARTIFACT=$1
NEXUS_URI=$2

if [ ! -d "$ARTIFACT" ]; then
	echo "Artifact directory must be provided"
	usage
fi


if [ -z "$NEXUS_URI" ]; then
	echo "Nexus uri must be specified"
	usage
fi

cd "$ARTIFACT"


STAGING_DIR="./staging"
GIT_ARTIFACT="./tag-artifact.git"

if [ ! -d "$STAGING_DIR" ]; then
	echo "No stating artifact found at $ARTIFACT"
	usage
fi

if [ ! -d "$GIT_ARTIFACT" ]; then
	echo "No git artifact found at $ARTIFACT"
	usage
fi


echo "Using:"
echo "stagingDir=$STAGING_DIR"
echo "gitArtifact=$GIT_ARTIFACT"
echo "nexusUri=$NEXUS_URI"
echo ""

exit 1
#######################################################################
#                       Release all files to nexus using http PUT
########################################################################

echo "Releasing $STAGING_DIR to nexus"
for file in $(find . -type f); do
        curl "${NEXUS_URI}${file:2}" --upload-file "$file"
done

########################################################################
#                       Push all tags from staging artifact to master
########################################################################

echo "Push all tags from $GIT_ARTIFACT_DIR"
cd $GIT_ARTIFACT_DIR
git push origin --tags

